// Code generated by protoc-gen-go. DO NOT EDIT.
// source: param.grpc

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// A compilation error at this line likely means your copy of the
// grpc package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the grpc package

// 请求结构体
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e1747c98d2fc1d5, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 回复结构体
type HelloReply struct {
	Message              string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e1747c98d2fc1d5, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *HelloReply) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "jt808.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "jt808.HelloReply")
}

func init() { proto.RegisterFile("param.grpc", fileDescriptor_1e1747c98d2fc1d5) }

var fileDescriptor_1e1747c98d2fc1d5 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xbf, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x15, 0x41, 0x81, 0xba, 0x2c, 0x98, 0x25, 0xca, 0x42, 0x95, 0xa9, 0x93, 0x8d, 0xc2,
	0x52, 0xc4, 0x04, 0x0b, 0xb0, 0x06, 0x26, 0x96, 0xe8, 0x1a, 0xae, 0xc6, 0xc8, 0xbf, 0xb0, 0x2f,
	0x48, 0xf9, 0xef, 0x91, 0x9c, 0x46, 0xa2, 0xdb, 0xf3, 0xd3, 0x27, 0xdf, 0x77, 0xc7, 0x56, 0x01,
	0x22, 0x58, 0x11, 0xa2, 0x27, 0xcf, 0x17, 0xdf, 0xb4, 0xbd, 0xdd, 0x56, 0x37, 0xca, 0x7b, 0x65,
	0x50, 0xe6, 0x72, 0x37, 0xec, 0x25, 0x69, 0x8b, 0x89, 0xc0, 0x86, 0x89, 0xab, 0x6b, 0x76, 0xf9,
	0x82, 0xc6, 0xf8, 0x16, 0x7f, 0x06, 0x4c, 0xc4, 0x39, 0x3b, 0x75, 0x60, 0xb1, 0x2c, 0xd6, 0xc5,
	0x66, 0xd9, 0xe6, 0x5c, 0x03, 0x63, 0x07, 0x26, 0x98, 0x91, 0x97, 0xec, 0xdc, 0x62, 0x4a, 0xa0,
	0x66, 0x68, 0x7e, 0xf2, 0x7b, 0xc6, 0xfa, 0x88, 0x40, 0xf8, 0xd9, 0x01, 0x95, 0x27, 0xeb, 0x62,
	0xb3, 0x6a, 0x2a, 0x31, 0x19, 0x88, 0xd9, 0x40, 0xbc, 0xcf, 0x06, 0xed, 0xf2, 0x40, 0x3f, 0x52,
	0xf3, 0xc0, 0x16, 0x79, 0x04, 0x6f, 0xd8, 0xc5, 0x1b, 0x8c, 0x53, 0xbe, 0x16, 0x79, 0x09, 0xf1,
	0x5f, 0xb0, 0xba, 0x3a, 0x2e, 0x83, 0x19, 0x9f, 0x5e, 0x3f, 0x9e, 0x95, 0x26, 0x44, 0xd1, 0x7b,
	0x2b, 0x0d, 0x68, 0xe3, 0x9d, 0xfa, 0x1a, 0xb4, 0x24, 0x8c, 0x56, 0x3b, 0x30, 0x9d, 0x76, 0x7b,
	0xdf, 0x25, 0x8c, 0xbf, 0xba, 0x47, 0xa9, 0x1d, 0x61, 0x74, 0x60, 0xa6, 0x9b, 0xf4, 0xde, 0xc8,
	0xfc, 0xa1, 0x54, 0x31, 0xf4, 0xbb, 0xb3, 0x5c, 0xde, 0xfd, 0x05, 0x00, 0x00, 0xff, 0xff, 0x01,
	0x45, 0x8d, 0x73, 0x4c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloClient is the client API for Hello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/jt808.Hello/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServer is the server API for Hello service.
type HelloServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

// UnimplementedHelloServer can be embedded to have forward compatible implementations.
type UnimplementedHelloServer struct {
}

func (*UnimplementedHelloServer) SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jt808.Hello/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "jt808.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Hello_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "param.grpc",
}
